//
//  ClassicCard.swift
//  Lilith
//
//  Created by Mikhail Bukhrashvili on 21.09.24.
//

import Foundation

protocol CardsInfoProtocol {
    var id: String { get }
    var title: String { get }
    var subTitle: String { get }
    var description: String { get }
    var cards: [Card] { get }
}


final class ClassicCard: CardsInfoProtocol, Identifiable {
    let id = "Rider Waite"
    let title = "Колода Таро"
    let subTitle = "Райдер Уэйт"
    let description = ""
    
    let cards: [Card] = [
        Card(
            id: "RIDER WAITE - СLASSIC - THE FOOL",
            title: "Шут",
            element: .air,
            arkan: .major,
            astrology: Astrology(planet: .uranus, zodiac: nil, description: nil),
            numerology: Numerology(number: "0", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE MAGICIAN",
            title: "Маг",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .mercury, zodiac: nil, description: nil),
            numerology: Numerology(number: "1", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE HIGH PRIESTESS",
            title: "Верховная Жрица",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .moon, zodiac: nil, description: nil),
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE EMPRESS",
            title: "Императрица",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .venus, zodiac: nil, description: nil),
            numerology: Numerology(number: "3", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE EMPEROR",
            title: "Император",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .aries, description: nil),
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE HIEROPHANT",
            title: "Иерофант",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .taurus, description: nil),
            numerology: Numerology(number: "5", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE LOVERS",
            title: "Влюблённые",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .gemini, description: nil),
            numerology: Numerology(number: "6", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE CHARIOT",
            title: "Колесница",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .cancer, description: nil),
            numerology: Numerology(number: "7", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - STRENGTH",
            title: "Сила",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .libra, description: nil),
            numerology: Numerology(number: "8", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE HERMIT",
            title: "Отшельник",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .virgo, description: nil),
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - WHEEL OF FORTUNE",
            title: "Колесо Фортуны",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .jupiter, zodiac: nil, description: nil),
            numerology: Numerology(number: "10", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - JUSTICE",
            title: "Справедливость",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .leo, description: nil),
            numerology: Numerology(number: "11", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE HANGED MAN",
            title: "Повешенный",
            element: .water,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: nil, description: nil),
            numerology: Numerology(number: "12", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - DEATH",
            title: "Смерть",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .scorpio, description: nil),
            numerology: Numerology(number: "13", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - TEMPERANCE",
            title: "Умеренность",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .sagittarius, description: nil),
            numerology: Numerology(number: "14", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE DEVIL",
            title: "Дьявол",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .capricorn, description: nil),
            numerology: Numerology(number: "15", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE TOWER",
            title: "Башня",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .mars, zodiac: nil, description: nil),
            numerology: Numerology(number: "16", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE STAR",
            title: "Звезда",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .aquarius, description: nil),
            numerology: Numerology(number: "17", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE MOON",
            title: "Луна",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: nil, zodiac: .pisces, description: nil),
            numerology: Numerology(number: "18", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE SUN",
            title: "Солнце",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .sun, zodiac: nil, description: nil),
            numerology: Numerology(number: "19", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - JUDGEMENT",
            title: "Суд",
            element: .fire,
            arkan: .major,
            astrology: Astrology(planet: .pluto, zodiac: nil, description: nil),
            numerology: Numerology(number: "20", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - THE WORLD",
            title: "Мир",
            element: nil,
            arkan: .major,
            astrology: Astrology(planet: .saturn, zodiac: nil, description: nil),
            numerology: Numerology(number: "21", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - СLASSIC - ACE OF WANDS",
            title: "Туз Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "1", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TWO OF WANDS",
            title: "Двойка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - THREE OF WANDS",
            title: "Тройка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "3", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FOUR OF WANDS",
            title: "Четвёрка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FIVE OF WANDS",
            title: "Пятёрка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "5", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SIX OF WANDS",
            title: "Шестёрка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "6", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SEVEN OF WANDS",
            title: "Семёрка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "7", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - EIGHT OF WANDS",
            title: "Восьмёрка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "8", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - NINE OF WANDS",
            title: "Девятка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TEN OF WANDS",
            title: "Десятка Жезлов",
            element: .fire,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "10", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - ACE OF SWORDS",
            title: "Туз Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "1", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TWO OF SWORDS",
            title: "Двойка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - THREE OF SWORDS",
            title: "Тройка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "3", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FOUR OF SWORDS",
            title: "Четвёрка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FIVE OF SWORDS",
            title: "Пятёрка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "5", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SIX OF SWORDS",
            title: "Шестёрка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "6", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SEVEN OF SWORDS",
            title: "Семёрка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "7", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - EIGHT OF SWORDS",
            title: "Восьмёрка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "8", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - NINE OF SWORDS",
            title: "Девятка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TEN OF SWORDS",
            title: "Десятка Мечей",
            element: .air,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "10", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - ACE OF CUPS",
            title: "Туз Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "1", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TWO OF CUPS",
            title: "Двойка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - THREE OF CUPS",
            title: "Тройка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "3", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FOUR OF CUPS",
            title: "Четвёрка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FIVE OF CUPS",
            title: "Пятёрка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "5", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SIX OF CUPS",
            title: "Шестёрка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "6", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SEVEN OF CUPS",
            title: "Семёрка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "7", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - EIGHT OF CUPS",
            title: "Восьмёрка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "8", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - NINE OF CUPS",
            title: "Девятка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TEN OF CUPS",
            title: "Десятка Кубков",
            element: .water,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "10", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - ACE OF PENTACLES",
            title: "Туз Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "1", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TWO OF PENTACLES",
            title: "Двойка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - THREE OF PENTACLES",
            title: "Тройка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "3", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FOUR OF PENTACLES",
            title: "Четвёрка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - FIVE OF PENTACLES",
            title: "Пятёрка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "5", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SIX OF PENTACLES",
            title: "Шестёрка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "6", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - SEVEN OF PENTACLES",
            title: "Семёрка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "7", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - EIGHT OF PENTACLES",
            title: "Восьмёрка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "8", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - NINE OF PENTACLES",
            title: "Девятка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - TEN OF PENTACLES",
            title: "Десятка Пентаклей",
            element: .earth,
            arkan: .minor,
            astrology: nil,
            numerology: Numerology(number: "10", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - PAGE OF WANDS",
            title: "Паж Жезлов",
            element: .fire,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KNIGHT OF WANDS",
            title: "Рыцарь Жезлов",
            element: .fire,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - QUEEN OF WANDS",
            title: "Королева Жезлов",
            element: .fire,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KING OF WANDS",
            title: "Король Жезлов",
            element: .fire,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - PAGE OF SWORDS",
            title: "Паж Мечей",
            element: .air,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KNIGHT OF SWORDS",
            title: "Рыцарь Мечей",
            element: .air,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - QUEEN OF SWORDS",
            title: "Королева Мечей",
            element: .air,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KING OF SWORDS",
            title: "Король Мечей",
            element: .air,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - PAGE OF CUPS",
            title: "Паж Кубков",
            element: .water,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KNIGHT OF CUPS",
            title: "Рыцарь Кубков",
            element: .water,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - QUEEN OF CUPS",
            title: "Королева Кубков",
            element: .water,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KING OF CUPS",
            title: "Король Кубков",
            element: .water,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - PAGE OF PENTACLES",
            title: "Паж Пентаклей",
            element: .earth,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KNIGHT OF PENTACLES",
            title: "Рыцарь Пентаклей",
            element: .earth,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - QUEEN OF PENTACLES",
            title: "Королева Пентаклей",
            element: .earth,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "RIDER WAITE - CLASSIC - KING OF PENTACLES",
            title: "Король Пентаклей",
            element: .earth,
            arkan: .court,
            astrology: nil,
            numerology: Numerology(number: "No value", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        )
    ]
}

final class OtherCard: CardsInfoProtocol {
    let id = "Other"
    let title = "Колода Таро"
    let subTitle = "Кастомная"
    let description = ""
    
    let cards: [Card] = [
        Card(
            id: "1",
            title: "Просто очень длинное название",
            element: .air,
            arkan: .major,
            astrology: Astrology(planet: .uranus, zodiac: nil, description: nil),
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "2",
            title: "El Caballero de Pentáculos",
            element: .air,
            arkan: .major,
            astrology: Astrology(planet: .uranus, zodiac: nil, description: nil),
            numerology: Numerology(number: "9", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "3",
            title: "Der Ritter der Schwerter",
            element: .air,
            arkan: .major,
            astrology: Astrology(planet: .venus, zodiac: nil, description: nil),
            numerology: Numerology(number: "2", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "4",
            title: "ფენტაკლების დედოფალი",
            element: .water,
            arkan: .major,
            astrology: Astrology(planet: .mars, zodiac: .pisces, description: nil),
            numerology: Numerology(number: "12", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "5",
            title: "Le Chevalier de Pentacles",
            element: .fire,
            arkan: .major,
            astrology: Astrology(planet: .uranus, zodiac: .aries, description: nil),
            numerology: Numerology(number: "4", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "6",
            title: "The Queen of Pentacles",
            element: .earth,
            arkan: .minor,
            astrology: Astrology(planet: .sun, zodiac: .capricorn, description: nil),
            numerology: Numerology(number: "15", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "7",
            title: "Il Cavaliere di Denari",
            element: .earth,
            arkan: .minor,
            astrology: Astrology(planet: .sun, zodiac: .capricorn, description: nil),
            numerology: Numerology(number: "15", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "8",
            title: "ملكة الخماسيات",
            element: .earth,
            arkan: .court,
            astrology: Astrology(planet: .sun, zodiac: .capricorn, description: nil),
            numerology: Numerology(number: "15", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        ),
        Card(
            id: "9",
            title: "ペンタクルの騎士",
            element: .earth,
            arkan: .court,
            astrology: Astrology(planet: .sun, zodiac: .capricorn, description: nil),
            numerology: Numerology(number: "15", descriptions: nil),
            filosophy: nil,
            mainMeaning: nil,
            personalityCharacterization: nil,
            answer: nil
        )
        ]
    }
